#!/usr/bin/env bash
set -e

# # Run formatting check before commit
# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# cd "$DIR/.."
#
# # Run zig fmt check
# zig fmt --check .
